[pytest]
DJANGO_SETTINGS_MODULE = expendituresTracer.settings

env = 
    EXPENDITURES_TRACER_API_RUN_MODE=test

python_files=test_*.py

addopts=-v --ignore=env --cov=. --cov-report=html

log_cli = 1
log_cli_level=WARN
log_cli_format=%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S