"""
Django settings for expendituresTracer project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from logging import getLogger
from pathlib import Path
import os
from corsheaders.defaults import default_headers

logger = getLogger("expendituresTracer.settings")

RUN_MODE = os.environ.get("EXPENDITURES_TRACER_API_RUN_MODE", "development")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

VERSION_FILE = os.path.join(BASE_DIR, "version.json")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["EXPENDITURES_TRACER_API_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (RUN_MODE != "production") or os.environ.get(
    "EXPENDITURES_TRACER_API_DEBUG", "false"
).lower() == "true"

ALLOWED_HOSTS = []
ALLOWED_HOSTS_ENV = os.environ.get("EXPENDITURES_TRACER_API_ALLOWED_HOSTS", None)
if RUN_MODE == "development":
    ALLOWED_HOSTS.extend(["127.0.0.1", "localhost"])
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS.extend(ALLOWED_HOSTS_ENV.split(","))

# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "main",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "django_celery_results",
    "django_celery_beat",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "api_v3.middleware.parseQueryString",
    "api_v3.middleware.parseMonth",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "expendituresTracer.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "expendituresTracer.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ["POSTGRES_USER"],
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],
        "HOST": os.environ["POSTGRES_HOST"],
        "PORT": os.environ["POSTGRES_PORT"],
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Rome"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "COERCE_DECIMAL_TO_STRING": False,
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "main.security.CSRFExemptSessionAuthentication",
    ),
    "EXCEPTION_HANDLER": "api_v3.exception_handler.custom_exception_handler",
}

# CORS settings
CORS_ALLOW_CREDENTIALS = RUN_MODE == "development"
CORS_ALLOWED_ORIGINS = []
if RUN_MODE == "development":
    CORS_ALLOWED_ORIGINS.extend(
        [
            "http://127.0.0.1:5173",
            "http://localhost:5173",
        ]
    )
CORS_ALLOWED_ORIGINS_ENV = os.environ.get(
    "EXPENDITURES_TRACER_API_CORS_ALLOWED_ORIGINS", ""
)
if CORS_ALLOWED_ORIGINS_ENV:
    CORS_ALLOWED_ORIGINS.extend(CORS_ALLOWED_ORIGINS_ENV.split(","))

CORS_ALLOW_HEADERS = list(default_headers) + ["month", "db"]

# CELERY
RABBITMQ = {
    "PROTOCOL": "amqp",
    "HOST": os.environ.get("EXPENDITURES_TRACER_API_RABBITMQ_HOST", "127.0.0.1"),
    "PORT": os.environ.get("EXPENDITURES_TRACER_API_RABBITMQ_PORT", 5672),
    "USER": os.environ.get("EXPENDITURES_TRACER_API_RABBITMQ_USER", "guest"),
    "PASSWORD": os.environ.get("EXPENDITURES_TRACER_API_RABBITMQ_PASSWORD", "guest"),
}

CELERY_BROKER_URL = f"{RABBITMQ['PROTOCOL']}://{RABBITMQ['USER']}:{RABBITMQ['PASSWORD']}@{RABBITMQ['HOST']}:{RABBITMQ['PORT']}"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = TIME_ZONE


# BACKUP SETTINGS
MAX_DUMP_FILES = 5
