# Generated by Django 3.1.4 on 2021-02-15 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('users', models.ManyToManyField(related_name='dbs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateTimeField(null=True)),
                ('is_expected', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='main.category')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='main.database')),
                ('expected_expenditure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenditures', to='main.expenditure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.database'),
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateTimeField(auto_now=True)),
                ('reference_date', models.DateTimeField()),
                ('income', models.BooleanField(default=False)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashes', to='main.database')),
            ],
        ),
    ]
